#!/bin/sh
set -e

case "$1" in
    remove)
        /usr/sbin/service rexster stop
    ;;

    upgrade|deconfigure|failed-upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
